services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tradingview-app
    ports:
      - "${PORT}:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1